spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: user
    password: passer
    url: jdbc:h2:mem:student-management
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

server:
  error:
    include-message: always
    include-binding-errors: always
